# Generated by Django 2.1.5 on 2020-06-24 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('YearOfRelease', models.IntegerField()),
                ('Borrowed', models.BooleanField()),
                ('Returned', models.BooleanField()),
                ('BorrowedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Borrowed')),
                ('ReturnDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Returned')),
            ],
        ),
    ]
